version: 1.0
app:
  # build id to deploy
  # version: 1.0-SNAPSHOT-20230716015630
  # number of instances
  services:
    - crn: 'crn:v1:staging:public:mqcloud:eu-de:a/aa9cfb05a0941e285ba634bef0a58eda:0652c728-ce10-4f77-87a3-c960bd4bb04f::'
  instances:
    # q: consider availability zones? 

    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    # q: what's the overall limit?
    max: 3
  resources:
    # max cpu, defaults to 1 cpu limit, half of that for min, min >= 1
    # q: what's the overall limit?
    # q: do we support fractions?
    cpu: 1
  version: 569ca663-f774-41fb-9c5d-1b7908d04388
# probes
# dynamic scaling
# scaling to 0
